"""AI Daily Brief — morning operations summary generated by Groq."""
import _path_setup  # noqa: F401
import streamlit as st
from datetime import datetime

from backend import brief as brief_mod


st.set_page_config(page_title="Daily Brief — El Camino", page_icon="📋", layout="wide")
st.title("📋 Daily Brief")
st.caption("AI-generated morning summary of your business. Powered by Groq.")


if "brief_text" not in st.session_state:
    st.session_state.brief_text = None
if "brief_generated_at" not in st.session_state:
    st.session_state.brief_generated_at = None


def generate():
    with st.spinner("Analyzing your business data..."):
        try:
            st.session_state.brief_text = brief_mod.generate_daily_brief()
            st.session_state.brief_generated_at = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        except Exception as e:
            st.session_state.brief_text = None
            st.error(f"Failed to generate brief: {e}")


# Auto-generate on first load
if st.session_state.brief_text is None:
    generate()

col1, col2 = st.columns([6, 1])
with col2:
    if st.button("Regenerate", use_container_width=True):
        generate()
        st.rerun()

if st.session_state.brief_generated_at:
    st.caption(f"Generated: {st.session_state.brief_generated_at}")

if st.session_state.brief_text:
    st.markdown("---")
    st.markdown(st.session_state.brief_text)
